version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: premium-app-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - DATABASE_PATH=/app/data/bot_database.db
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/bot_database.db').close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local